/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVitalsRouteImport } from './routes/_app.vitals'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppPrescriptionsRouteImport } from './routes/_app.prescriptions'
import { Route as AppPharmacyRouteImport } from './routes/_app.pharmacy'
import { Route as AppPatientsRouteImport } from './routes/_app.patients'
import { Route as AppMyPrescriptionsRouteImport } from './routes/_app.my-prescriptions'
import { Route as AppMyBillsRouteImport } from './routes/_app.my-bills'
import { Route as AppMyAppointmentsRouteImport } from './routes/_app.my-appointments'
import { Route as AppDoctorsRouteImport } from './routes/_app.doctors'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppBedsRouteImport } from './routes/_app.beds'
import { Route as AppAppointmentsRouteImport } from './routes/_app.appointments'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVitalsRoute = AppVitalsRouteImport.update({
  id: '/vitals',
  path: '/vitals',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPrescriptionsRoute = AppPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => AppRoute,
} as any)
const AppPharmacyRoute = AppPharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsRoute = AppPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AppRoute,
} as any)
const AppMyPrescriptionsRoute = AppMyPrescriptionsRouteImport.update({
  id: '/my-prescriptions',
  path: '/my-prescriptions',
  getParentRoute: () => AppRoute,
} as any)
const AppMyBillsRoute = AppMyBillsRouteImport.update({
  id: '/my-bills',
  path: '/my-bills',
  getParentRoute: () => AppRoute,
} as any)
const AppMyAppointmentsRoute = AppMyAppointmentsRouteImport.update({
  id: '/my-appointments',
  path: '/my-appointments',
  getParentRoute: () => AppRoute,
} as any)
const AppDoctorsRoute = AppDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppBedsRoute = AppBedsRouteImport.update({
  id: '/beds',
  path: '/beds',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/appointments': typeof AppAppointmentsRoute
  '/beds': typeof AppBedsRoute
  '/billing': typeof AppBillingRoute
  '/dashboard': typeof AppDashboardRoute
  '/doctors': typeof AppDoctorsRoute
  '/my-appointments': typeof AppMyAppointmentsRoute
  '/my-bills': typeof AppMyBillsRoute
  '/my-prescriptions': typeof AppMyPrescriptionsRoute
  '/patients': typeof AppPatientsRoute
  '/pharmacy': typeof AppPharmacyRoute
  '/prescriptions': typeof AppPrescriptionsRoute
  '/settings': typeof AppSettingsRoute
  '/vitals': typeof AppVitalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/appointments': typeof AppAppointmentsRoute
  '/beds': typeof AppBedsRoute
  '/billing': typeof AppBillingRoute
  '/dashboard': typeof AppDashboardRoute
  '/doctors': typeof AppDoctorsRoute
  '/my-appointments': typeof AppMyAppointmentsRoute
  '/my-bills': typeof AppMyBillsRoute
  '/my-prescriptions': typeof AppMyPrescriptionsRoute
  '/patients': typeof AppPatientsRoute
  '/pharmacy': typeof AppPharmacyRoute
  '/prescriptions': typeof AppPrescriptionsRoute
  '/settings': typeof AppSettingsRoute
  '/vitals': typeof AppVitalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/appointments': typeof AppAppointmentsRoute
  '/_app/beds': typeof AppBedsRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/doctors': typeof AppDoctorsRoute
  '/_app/my-appointments': typeof AppMyAppointmentsRoute
  '/_app/my-bills': typeof AppMyBillsRoute
  '/_app/my-prescriptions': typeof AppMyPrescriptionsRoute
  '/_app/patients': typeof AppPatientsRoute
  '/_app/pharmacy': typeof AppPharmacyRoute
  '/_app/prescriptions': typeof AppPrescriptionsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/vitals': typeof AppVitalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/appointments'
    | '/beds'
    | '/billing'
    | '/dashboard'
    | '/doctors'
    | '/my-appointments'
    | '/my-bills'
    | '/my-prescriptions'
    | '/patients'
    | '/pharmacy'
    | '/prescriptions'
    | '/settings'
    | '/vitals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/analytics'
    | '/appointments'
    | '/beds'
    | '/billing'
    | '/dashboard'
    | '/doctors'
    | '/my-appointments'
    | '/my-bills'
    | '/my-prescriptions'
    | '/patients'
    | '/pharmacy'
    | '/prescriptions'
    | '/settings'
    | '/vitals'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/analytics'
    | '/_app/appointments'
    | '/_app/beds'
    | '/_app/billing'
    | '/_app/dashboard'
    | '/_app/doctors'
    | '/_app/my-appointments'
    | '/_app/my-bills'
    | '/_app/my-prescriptions'
    | '/_app/patients'
    | '/_app/pharmacy'
    | '/_app/prescriptions'
    | '/_app/settings'
    | '/_app/vitals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vitals': {
      id: '/_app/vitals'
      path: '/vitals'
      fullPath: '/vitals'
      preLoaderRoute: typeof AppVitalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prescriptions': {
      id: '/_app/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof AppPrescriptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pharmacy': {
      id: '/_app/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof AppPharmacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients': {
      id: '/_app/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AppPatientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-prescriptions': {
      id: '/_app/my-prescriptions'
      path: '/my-prescriptions'
      fullPath: '/my-prescriptions'
      preLoaderRoute: typeof AppMyPrescriptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-bills': {
      id: '/_app/my-bills'
      path: '/my-bills'
      fullPath: '/my-bills'
      preLoaderRoute: typeof AppMyBillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-appointments': {
      id: '/_app/my-appointments'
      path: '/my-appointments'
      fullPath: '/my-appointments'
      preLoaderRoute: typeof AppMyAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/doctors': {
      id: '/_app/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof AppDoctorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/beds': {
      id: '/_app/beds'
      path: '/beds'
      fullPath: '/beds'
      preLoaderRoute: typeof AppBedsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appointments': {
      id: '/_app/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAppointmentsRoute: typeof AppAppointmentsRoute
  AppBedsRoute: typeof AppBedsRoute
  AppBillingRoute: typeof AppBillingRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDoctorsRoute: typeof AppDoctorsRoute
  AppMyAppointmentsRoute: typeof AppMyAppointmentsRoute
  AppMyBillsRoute: typeof AppMyBillsRoute
  AppMyPrescriptionsRoute: typeof AppMyPrescriptionsRoute
  AppPatientsRoute: typeof AppPatientsRoute
  AppPharmacyRoute: typeof AppPharmacyRoute
  AppPrescriptionsRoute: typeof AppPrescriptionsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppVitalsRoute: typeof AppVitalsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAppointmentsRoute: AppAppointmentsRoute,
  AppBedsRoute: AppBedsRoute,
  AppBillingRoute: AppBillingRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDoctorsRoute: AppDoctorsRoute,
  AppMyAppointmentsRoute: AppMyAppointmentsRoute,
  AppMyBillsRoute: AppMyBillsRoute,
  AppMyPrescriptionsRoute: AppMyPrescriptionsRoute,
  AppPatientsRoute: AppPatientsRoute,
  AppPharmacyRoute: AppPharmacyRoute,
  AppPrescriptionsRoute: AppPrescriptionsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppVitalsRoute: AppVitalsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
