package com.hms.backend.patients.dto;

import lombok.Builder;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@Builder
public class PatientRegistrationResponse {

    private String message;

    private PatientResponse patient;

    private String username;

    private String temporaryPassword;

    private Boolean credentialsAutoGenerated;
}